# Site settings
title:            "Sawa's world" # 添加博客标题
author:           Sawa # 添加你的名字
logo:             hp_cat.png # 添加博客 Logo
avatar:           u=4242152899,2079802517&fm=21&gp=0.jpg # 添加你的头像
favicon:          hp_cat.ico # 添加用于显示于浏览器 Tab 上的博客图标
email:            chousawa@gmail.com
description: >    # 主题简介，可改为博客描述
  只是个还有点用处的人罢了。

url:              "chousawa.github.io" # 添加域名（不需要 http:// 前缀），或使用「/」作为博客根链接，
baseurl:          "" # the subpath of your site, e.g. /blog/

twitter:          chousawa# 添加你的 Twitter 用户名
github:           chousawa # 添加你的 GitHub 用户名
disqus:           # 添加你的 Disqus 评论工具站点名

permalink:        /:title
paginate:         5

# Build settings
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

gems:
  - jekyll-sitemap
  - jekyll-paginate
